In [32]:
print("======================SkLearn - Model Selection - Train_Test_Split!=========================================")
print("==================================================================================================")

======================SkLearn - Model Selection - Train_Test_Split!=========================================


In [33]:
# Import numpy as np
# Import train_test_split from sklearn.model_selection
# Define Variable X, y as 'numpy.ndarray' and 'range' with Defined Range and Shape Parameters:

import numpy as np
from sklearn.model_selection import train_test_split

X, y = np.arange(20).reshape(10,2), range(10)

In [47]:
# Print the Type of Variable X with Values:

print(type(X))
X

<class 'numpy.ndarray'>


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [48]:
# Print the Type of Variable y with Range:

print(type(y))
y

<class 'range'>


range(0, 10)

In [36]:
# Print the Type of Variable y with Range-Values:

list(y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
# Splitting Of TRAIN-TEST Data Percentage with A Random State Variable Used to Shuffle Values: Case 01
# Fixed Value for Random State with a Fixed % Vale of Test Data will Always Create Fixed Values-Size of Train-Test Data:

X_train,x_test,Y_train, y_test = train_test_split(X,y,test_size = 0.25, random_state = 10)

In [38]:
# Display the Type and Value of: X_train

print(type(X_train))
X_train

<class 'numpy.ndarray'>


array([[12, 13],
       [ 6,  7],
       [ 2,  3],
       [ 0,  1],
       [14, 15],
       [ 8,  9],
       [18, 19]])

In [39]:
# Display the Type and Value of: x_test
print(type(x_test))
x_test

<class 'numpy.ndarray'>


array([[16, 17],
       [ 4,  5],
       [10, 11]])

In [40]:
# Display the Type and Value of: Y_train

print(type(Y_train))
Y_train

<class 'list'>


[6, 3, 1, 0, 7, 4, 9]

In [41]:
# Display the Type and Value of: y_test

print(type(y_test))
y_test

<class 'list'>


[8, 2, 5]

In [42]:
# Splitting Of 'TRAIN-TEST' Data Percentage with A 'Random State' Variable Used to Shuffle Values: Case 02
# Fixed Value for Random State with a Fixed % Vale of Test Data will Always Create Fixed Values-Size of Train-Test Data:

X_train,x_test,Y_train, y_test = train_test_split(X,y,test_size = 0.25, random_state = 20)

In [43]:
# Display the Type and Value of: X_train
print(type(X_train))
X_train

<class 'numpy.ndarray'>


array([[10, 11],
       [ 0,  1],
       [ 4,  5],
       [12, 13],
       [18, 19],
       [ 8,  9],
       [ 6,  7]])

In [44]:
# Display the Type and Value of: x_test

print(type(x_test))
x_test

<class 'numpy.ndarray'>


array([[14, 15],
       [ 2,  3],
       [16, 17]])

In [45]:
# Display the Type and Value of: Y_train

print(type(Y_train))
Y_train

<class 'list'>


[5, 0, 2, 6, 9, 4, 3]

In [46]:
# Display the Type and Value of: y_test

print(type(y_test))
y_test

<class 'list'>


[7, 1, 8]

In [50]:
# Split the Variable(Array/Range) into Train-Test Data as per Defined % and Defined shuffle value:False

train_test_split(y, shuffle = False)

[[0, 1, 2, 3, 4, 5, 6], [7, 8, 9]]

In [51]:
# Split the Variable(Array/Range) into Train-Test Data as per Defined % and Defined shuffle value:True

train_test_split(y, shuffle = True)

[[3, 4, 1, 8, 7, 6, 5], [2, 0, 9]]

In [52]:
# Split the Variable(Array/Range) into Train-Test Data as per Defined % and Defined shuffle value:False

train_test_split(X, shuffle = False)

[array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13]]),
 array([[14, 15],
        [16, 17],
        [18, 19]])]

In [53]:
# Split the Variable(Array/Range) into Train-Test Data as per Defined % and Defined shuffle value:True

train_test_split(X, shuffle = True)

[array([[14, 15],
        [ 2,  3],
        [ 0,  1],
        [12, 13],
        [10, 11],
        [16, 17],
        [ 4,  5]]),
 array([[ 8,  9],
        [18, 19],
        [ 6,  7]])]

In [54]:
# Split the Variable(Array/Range) into Train-Test Data as per Defined % = 50% and Defined shuffle value:True

train_test_split(X, test_size=.50, shuffle = True)

[array([[14, 15],
        [16, 17],
        [ 4,  5],
        [ 6,  7],
        [18, 19]]),
 array([[10, 11],
        [ 8,  9],
        [ 2,  3],
        [ 0,  1],
        [12, 13]])]